### ISSUE TITLE
nanoget is unable to parse information from BAM file without reference

### ISSUE THREAD

**Issue by jvhaarst** [wdecoster/nanoget#13]
Right now nanoget can't handle BAM files without reference, as used by PacBio for storing the output of their sequencers.
So right now I need to first extract the reads to FASTQ format, and then I can feed them to NanoPlot.
It would  be great if I could skip that step, to save time and space.

**Comment by jvhaarst** [comment]
Maybe this helps : http://pacificbiosciences.github.io/pbcore/pbcore.io.html#bam-format

**Comment by wdecoster** [comment]
Good suggestion, I can definitely have a look. Could you share or link me to an example dataset, so I can make sure it works?

**Comment by jvhaarst** [comment]
PacBio shares sample datasets.
The ones most suited for my application are here : https://github.com/PacificBiosciences/PacBioTestData/tree/master/data/SubreadSet

**Comment by wdecoster** [comment]
I plan to implement this feature by the end of the week - but as I'm also running against other deadlines I won't promise anything. Of course I welcome pull requests :-)

**Comment by wdecoster** [comment]
Thanks for your suggestion. NanoPlot should have an `--ubam` input option from v1.22.0. (available through pip).
