### ISSUE TITLE
License file is missing from pipy download - please tag your releases here

### ISSUE THREAD

**Issue by tillea** [wdecoster/nanoget#19]
Hi,
I intend to package nanoget for Debian.  Usually I prefer to package tagged releases from github since I frequently observed that downloads on pipy are incomplete.  Unfortunately here on Github you only have tag 1.0.0 while pipy has 1.12.1.  I'd consider it good style to tag your releases here as well.
The problem becomes obvious when checking the pipy tarball where the LICENSE file is missing.  This would be hard to accept for Debian since every software needs a license.
Could you please make sure that the pipy download is complete - or even more preferably could you tag your releases here.
BTW, besides a LICENSE a copyright is missing and I just have to wild guess that the owner of this Github project - Wouter De Coster - is the only copyright holder.  Please also specify this.
Thanks a lot, Andreas.

**Comment by wdecoster** [comment]
I've added the license, copyright and made a release. Please let me know if there is something I missed somewhere.
