### ISSUE TITLE
License was changed to GPL-3+ but setup.py remains at MIT

### ISSUE THREAD

**Issue by tillea** [wdecoster/nanoget#20]
Hi,
please use new license also in setup.py
Kind regards, Andreas.

**Comment by wdecoster** [comment]
Thanks for your patience, I think I've changed them all :)
Let me know if there is anything else I should take care of.

**Comment by tillea** [comment]
On Wed, Jun 17, 2020 at 04:00:34AM -0700, Wouter De Coster wrote:
> Thanks for your patience, I think I've changed them all :)

Thank you.

> Let me know if there is anything else I should take care of.

It should be fine now.  If you want new nanoget releases published in Debian feel free to ping
     Debian Med Packaging Team <debian-med-packaging@lists.alioth.debian.org>

Kind regards, Andreas.
