### ISSUE TITLE
GitHub releases?

### ISSUE THREAD

**Issue by nileshpatra** [wdecoster/nanoget#25]
Hi,

Thanks for your work on nanoget. The correct release (1.16.1 ) has been uploaded to PyPI, but it has not been tagged on github.
Actually, Debian python packages prefer github over PyPI, and it'd be awesome if you could tag the right release.
I could then update and upload the outdated package in Debian.

Let me know if more info is needed. Thanks!

===============================================================================================
CC: @wdecoster

**Comment by wdecoster** [comment]
Thanks for taking care of this. It took me way longer than it should, but here is https://github.com/wdecoster/nanoget/releases/tag/v1.16.1
