### ISSUE TITLE
New conda release

### ISSUE THREAD

**Issue by jchorl** [wdecoster/nanoget#34]
Hi! 

First, thanks for maintaining this!

I noticed the github releases are from 2021 and the conda install doesn't seem to include the latest changes.

What's the process for getting a new release out to conda? Anything I can help with there?

Thanks!

**Comment by wdecoster** [comment]
Aha, thanks for letting me know. Luckily it is not too much work, but easy to forget. I bumped the version on GitHub and pushed the changes to PyPI, which should _trigger_ a bioconda update. I will give it some time, and if not, change the bioconda recipe myself. I've also made a new GitHub release.

**Comment by jchorl** [comment]
Thank you!!!!

**Comment by wdecoster** [comment]
The bioconda bot took care of it: https://github.com/bioconda/bioconda-recipes/pull/43158
